Merge code base and homepage UI
tech-university-vietnam/1Car-FE pull request #4
Opened 2022-08-23 13:06 UTC by congvu24

2022-08-23 22:19 UTC, nina-hpn commented on src/components/SignUpModal.tsx
> +        'dateOfBirth',
Since we are not storing email and password, I don't think these fields are needed. For email we can decode from the access_token

2022-08-23 22:21 UTC, nina-hpn commented on src/components/SignUpModal.tsx
> +        'dateOfBirth',
Instead of using this for sign up, I think we can modify it for update a user information

2022-08-23 23:52 UTC, rkdixit96 requested changes
Wherever code is repeated...lets convert it into a sub component

2022-08-23 23:52 UTC, rkdixit96 commented on src/components/CarCard.tsx
> +        </div>
Lets convert these into sub components

2022-08-23 23:52 UTC, rkdixit96 commented on src/components/Header.tsx
> +      </ul>
Elements in this list as well can be sub components

2022-08-24 16:34 UTC, congvu24 commented on src/components/SignUpModal.tsx
> +        'dateOfBirth',
Since we don't need a sign up form, you can modify it to update user information for the first login. Hopefully you can do it after this merge

2022-08-24 16:43 UTC, congvu24 commented on src/components/Header.tsx
> +      </ul>
Thanks, fixed.

2022-08-24 16:43 UTC, congvu24 commented on src/components/CarCard.tsx
> +        </div>
Thanks, fixed.

2022-08-25 03:03 UTC, merged